#!/bin/bash

echo This action will overwrite all PDFs with conversions from EPS. Press enter to continue...

read

find . -name '*.eps' | while read i; do epstopdf "$i" ; echo -n . ; done

echo Done.
